version: '3.8' 

services:
  postgres:
    image: postgres:latest
    environment:

      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"  

  app:
    build: .   
    ports:
      - "3000:3000"
    depends_on:
      - postgres 
    volumes:
      - ./src:/app/src  
    environment:
      DB_HOST: postgres  
      DB_PORT: 5432
      NODE_ENV: development

volumes:
  postgres-data:  