const ErrorCodes = Object.freeze({
    '100000': {
        responseCode: '100000',
        text: 'ITEM_ALREADY_EXISTS',
        statusCode: 422,
        http_status_text: 'UNPROCESSABLE_ENTITY',
        message: 'item already exists',
        type: 'ClientError',
        module: 'GroceryItems',
    },
    '100001': {
        responseCode: '100001',
        text: 'ERROR_WHILE_ADDING_ITEMS',
        statusCode: 422,
        http_status_text: 'UNPROCESSABLE_ENTITY',
        message: 'Error while adding items.',
        type: 'ServerError',
        module: 'GroceryItems',
    },
    '100002': {
        responseCode: '100002',
        text: 'ERROR_WHILE_EDITING_ITEMS',
        statusCode: 422,
        http_status_text: 'UNPROCESSABLE_ENTITY',
        message: 'Error while editing items.',
        type: 'ServerError',
        module: 'GroceryItems',
    },
    '100003': {
        responseCode: '100003',
        text: 'ERROR_WHILE_GETTING_ITEMS',
        statusCode: 422,
        http_status_text: 'UNPROCESSABLE_ENTITY',
        message: 'Error while getting items.',
        type: 'ServerError',
        module: 'GroceryItems',
    },
    '100004': {
        responseCode: '100004',
        text: 'ERROR_WHILE_DELETETING_ITEMS',
        statusCode: 422,
        http_status_text: 'UNPROCESSABLE_ENTITY',
        message: 'Error while deleting items.',
        type: 'ServerError',
        module: 'GroceryItems',
    },
    '100005': {
        responseCode: '100005',
        text: 'ERROR_WHILE_UPDATING_INVENTORY',
        statusCode: 422,
        http_status_text: 'UNPROCESSABLE_ENTITY',
        message: 'Error While updating inventory.',
        type: 'ServerError',
        module: 'GroceryItems',
    },
    '100006': {
        responseCode: '100006',
        text: 'ITEM_NOT_FOUND',
        statusCode: 422,
        http_status_text: 'UNPROCESSABLE_ENTITY',
        message: 'Item not found.',
        type: 'ServerError',
        module: 'GroceryItems',
    },
    '100007': {
        responseCode: '100007',
        text: 'INSUFFICIENT_INVENTORY',
        statusCode: 422,
        http_status_text: 'UNPROCESSABLE_ENTITY',
        message: 'Insufficient inventory.',
        type: 'ClientError',
        module: 'GroceryItems',
    },
    '100008': {
        responseCode: '100008',
        text: 'INVALID_ACTION',
        statusCode: 422,
        http_status_text: 'UNPROCESSABLE_ENTITY',
        message: 'Invalid action',
        type: 'ClientError',
        module: 'GroceryItems',
    },
    '200000': {
        responseCode: '200000',
        text: 'INVALID_TYPE_OF_ITEMS',
        statusCode: 422,
        http_status_text: 'UNPROCESSABLE_ENTITY',
        message: 'Items must be defined and must be an array.',
        type: 'ClientError',
        module: 'OrderItems',
    },
    '200001': {
        responseCode: '200001',
        text: 'INSUFFICIENT_QUANTITY',
        statusCode: 422,
        http_status_text: 'UNPROCESSABLE_ENTITY',
        message: 'Insufficient quuatity.',
        type: 'ClientError',
        module: 'OrderItems',
    },
    '200002': {
        responseCode: '200002',
        text: 'ERROR_WHILE_ORDERING_ITEMS',
        statusCode: 422,
        http_status_text: 'UNPROCESSABLE_ENTITY',
        message: 'Error while ordering items.',
        type: 'ServerError',
        module: 'OrderItems',
    },
    '300000': {
        responseCode: '300000',
        text: 'USER_NOT_FOUND',
        statusCode: 422,
        http_status_text: 'UNPROCESSABLE_ENTITY',
        message: 'User not found.',
        type: 'ClientError',
        module: 'Users',
    },
    '300001': {
        responseCode: '300001',
        text: 'INVALID_PASSOWRD',
        statusCode: 422,
        http_status_text: 'UNPROCESSABLE_ENTITY',
        message: 'Invalid password',
        type: 'ClientError',
        module: 'Users',
    },
    '300002': {
        responseCode: '300002',
        text: 'ERROR_WHILE_GENERATING_TOKEN',
        statusCode: 500,
        http_status_text: 'UNPROCESSABLE_ENTITY',
        message: 'Error while generating token.',
        type: 'ServerError',
        module: 'Users',
    },
    '300003': {
        responseCode: '300003',
        text: 'USER_ALREADY_EXISTS',
        statusCode: 422,
        http_status_text: 'UNPROCESSABLE_ENTITY',
        message: 'User already exists.',
        type: 'ClientError',
        module: 'Users',
    },
    '300004': {
        responseCode: '300004',
        text: 'ERROR_WHILE_CREATING_USER',
        statusCode: 422,
        http_status_text: 'UNPROCESSABLE_ENTITY',
        message: 'Error while creating user.',
        type: 'ServerError',
        module: 'Users',
    },
    '300005': {
        responseCode: '300005',
        text: 'UN_AUTHORIZED',
        statusCode: 401,
        http_status_text: 'NOT_AUTHORIZED',
        message: 'Not authorized',
        type: 'ClientError',
        module: 'Users',
    },
    '300006': {
        responseCode: '300006',
        text: 'PERMISSION_DENIED',
        statusCode: 403,
        http_status_text: 'FORBIDDEN',
        message: 'Permission denied',
        type: 'ClientError',
        module: 'Users',
    },
})

export default ErrorCodes;
